modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/DAQEM/ItemRestrictions/issues"
license = "MIT"

[[mods]]
modId = "itemrestrictions"
version = "${version}"
displayName = "Item Restrictions"
authors = "DAQEM"
logoFile = "icon.png"
description = '''

'''
#logoFile = ""

[[dependencies.itemrestrictions]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemrestrictions]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemrestrictions]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.itemrestrictions]]
modId = "arc"
mandatory = true
versionRange = "[${arc_version},)"
ordering = "AFTER"
side = "BOTH"