org.gradle.jvmargs=-Xmx4096M

# Build Settings
enabled_platforms=fabric,neoforge

# Project
maven_group=com.daqem.itemrestrictions
archives_base_name=itemrestrictions
mod_version=19.1.0
mod_id=itemrestrictions
mod_name=Item Restrictions
mod_description=Item Restrictions is a mod that allows you to restrict the use of items based on certain conditions.
mod_author=DAQEM
mod_license=Apache-2.0
mod_website=https://daqem.com
mod_repository=https://github.com/DAQEM/ItemRestrictions

# Publishing
supported_minecraft_versions=1.21.11
release_type=release
curse_forge_project_id=887774
curse_forge_dependencies=architectury-api,ui,yaml-config,arc
modrinth_project_id=rU60qFq2
modrinth_dependencies=architectury-api,ui-lib,yaml-config,arc

# Dependencies
minecraft_version=1.21.11
parchment_version=1.21.11:2025.12.20
architectury_version=19.0.1
uilib_version=19.1.0
yamlconfig_version=19.1.0
arc_version=19.1.0

# Fabric
fabric_loader_version=0.18.4
fabric_api_version=0.141.3+1.21.11

# NeoForge
neoforge_version=21.11.38-beta

